version: "3"

services:
  nginx-proxy-image:
    image: nginx:alpine
    container_name: front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./certs:/etc/nginx/certs
# networks:
#   default:
#     external:
#       name: nginx-proxy
